### ISSUE TITLE
Add Support for Scenario Metadata

### ISSUE THREAD

**Issue by schmidni** [swiss-seismological-service/REIA-ws#7]
### User Story
As an end user of the webservice I would like to always get the correct metadata at the same endpoints no matter if it is a scenario or ria.

### Acceptance Criteria
The endpoints for metadata automatically return the data from other sources depending if it is a scenario or a ria. The respective field on the riskassessment can be used for this.

**Comment by schmidni** [comment]
Since the model is 
`Origin` --> `RiskAssessment`, and the information about scenarios is on the RiskAssessment this is a bit more difficult.

One option is to first check whether the OriginID exists on the `Earthquake Info Server`, if not also check the local db of the REIA installation.
It is also possible to set a flag in the config, or just omit the earthquake info server information, if the installation is purely used for scenarios.

**Comment by schmidni** [comment]
"Auswertung" is always "automatic".
"Magnitude Type" is always "Mw".

**Comment by kaestli** [comment]
Auswertung (if referring to to origin.m_evaluationmode) can be "automatic" or "manual". Typically, the first one is automatic, all later versions manual. (The d line has hardly any manually located origins, as the system is used for training purposes only.

Magnitude type of the magnitude used by USGS shakemap is Mw, as this is what the workflow is calibrated for. Note that those are typically no native magnitude assessments, but "conversions" from Ml / Mlhc. The conversion is done while preparing shakemap invocation. If you look up the magnitudes of the triggering origin, of events after 2009-01-01 the preferred Magnitude is typically Ml, which is typically Mw + 0.3, and typically no Mw is present (all with exceptions)
In a scenario case, if you get a request e.g. like "give me a scenario of 'the' Vallorcine 2005-09-09 mag. 4.4 event", you have to care yourself a) what the type of the indicated magnitude is, and b) what magnitude type your ground motion module is calibrated for.

**Comment by schmidni** [comment]
Thank you Philipp, probably I should have added, that `Auswertung` and `Magnitude` in this issue and context are only meant for the (OpenQuake) scenario calculations.

**Comment by romanoe** [comment]
For now, we use either the local database **OR** the earthquake database for scenarios. We will consider incorporating a mixed installation if necessary. Information regarding the database used for scenario retrieval will be managed in the configuration.

**Comment by schmidni** [comment]
@romanoe I think we can close this, no?
